#!/bin/sh

# old versions resided in /System/Library, remove.
rm -r /System/Library/StartupItems/tun

# Fix ownership and permissions. PackageMaker gets this wrong *sigh*
chown -R root:wheel /System/Library/StartupItems/tun
chmod -R u=rwX,g=rX,o=rX /System/Library/StartupItems/tun

# exit successfully
exit 0

